# Generated by Django 5.2.5 on 2025-08-10 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=64, unique=True)),
                ("order_date", models.DateField()),
                ("order_notes", models.TextField(blank=True, null=True)),
                ("delivery_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        choices=[("NMSLO", "NMSLO"), ("BLM", "BLM")], max_length=16
                    ),
                ),
                ("lease_number", models.CharField(max_length=128)),
                ("documents_links", models.JSONField(blank=True, default=list)),
                ("misc_index_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agency", "lease_number"),
                        name="uniq_agency_lease_number",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("RUNSHEET", "Runsheet"),
                            ("BASE_ABSTRACT", "Base Abstract"),
                            ("SUPPLEMENTAL_ABSTRACT", "Supplemental Abstract"),
                            ("DOL_ABSTRACT", "DOL Abstract"),
                        ],
                        max_length=32,
                    ),
                ),
                ("legal_description", models.TextField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("report_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leases",
                    models.ManyToManyField(
                        blank=True, related_name="reports", to="orders.lease"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
