# Generated by Django 5.2.5 on 2025-08-12 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_cloudlocation"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="runsheet_directory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="integrations.cloudlocation",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="runsheet_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="runsheet_report_found",
            field=models.BooleanField(default=False),
        ),
    ]
