# Generated by Django 5.2.5 on 2025-08-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_lease_runsheet_directory_lease_runsheet_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lease",
            old_name="runsheet_directory",
            new_name="runsheet_archive",
        ),
    ]
