# Generated by Django 5.2.5 on 2025-08-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(db_index=True, default="dropbox", max_length=32),
                ),
                ("path", models.CharField(db_index=True, max_length=1024)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_directory", models.BooleanField(default=True)),
                ("file_id", models.CharField(blank=True, max_length=256, null=True)),
                ("share_url", models.URLField(blank=True, null=True)),
                ("share_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "integrations_cloud_location",
                "indexes": [
                    models.Index(
                        fields=["provider", "path"],
                        name="integration_provide_0e4619_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "path"), name="uniq_provider_path"
                    )
                ],
            },
        ),
    ]
