# Generated by Django 5.2.5 on 2025-08-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_cloudlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyStorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        choices=[("NMSLO", "NMSLO"), ("BLM", "BLM")],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("runsheet_archive_base_path", models.CharField(max_length=1024)),
                ("documents_base_path", models.CharField(max_length=1024)),
                ("misc_index_base_path", models.CharField(max_length=1024)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agency Storage Configuration",
                "verbose_name_plural": "Agency Storage Configurations",
                "db_table": "integrations_agency_storage_config",
            },
        ),
    ]
