# Generated by Django 5.2.5 on 2025-08-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_agencystorageconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencystorageconfig",
            name="documents_base_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="agencystorageconfig",
            name="misc_index_base_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="agencystorageconfig",
            name="runsheet_archive_base_path",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
