# Generated by Django 5.2.5 on 2025-08-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_alter_agencystorageconfig_documents_base_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencystorageconfig",
            name="auto_create_lease_directories",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agencystorageconfig",
            name="runsheet_subfolder_documents_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agencystorageconfig",
            name="runsheet_subfolder_misc_index_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agencystorageconfig",
            name="runsheet_subfolder_runsheets_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
