# Generated by Django 5.2.5 on 2025-08-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_seed_agency_subfolder_defaults"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agencystorageconfig",
            old_name="auto_create_lease_directories",
            new_name="auto_create_runsheet_archives",
        ),
    ]
