# Generated by Django 5.2.7 on 2025-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_rename_auto_create_lease_directories_to_auto_create_runsheet_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencystorageconfig',
            name='auto_create_document_archives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agencystorageconfig',
            name='document_subfolder_agency_sourced_documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencystorageconfig',
            name='document_subfolder_unknown_sourced_documents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
