# Generated by Django 5.2.7 on 2025-10-27 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_agencystorageconfig_auto_create_document_archives_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasecampAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Basecamp account ID from OAuth authorization', max_length=255, unique=True)),
                ('account_name', models.CharField(help_text="Human-readable Basecamp account name (e.g., 'Acme Corp')", max_length=255)),
                ('access_token', models.TextField(help_text='Current OAuth access token for Basecamp API calls')),
                ('refresh_token_encrypted', models.TextField(help_text='Encrypted OAuth refresh token for long-term access')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp (optional, Basecamp tokens may not expire)', null=True)),
                ('scope', models.TextField(blank=True, default='', help_text='OAuth scope (empty for Basecamp 3 default full access)')),
                ('token_type', models.CharField(blank=True, default='Bearer', help_text="OAuth token type (typically 'Bearer')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When user first connected Basecamp account')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp (token refresh, etc.)')),
                ('user', models.OneToOneField(help_text='Application user who owns this Basecamp connection', on_delete=django.db.models.deletion.CASCADE, related_name='basecamp_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basecamp Account',
                'verbose_name_plural': 'Basecamp Accounts',
                'db_table': 'integrations_basecamp_account',
                'indexes': [models.Index(fields=['account_id'], name='integration_account_8ffb15_idx')],
            },
        ),
    ]
