# Generated by Django 5.2.7 on 2025-11-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_basecampaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxaccount',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="User's display name from Dropbox", max_length=255),
        ),
        migrations.AddField(
            model_name='dropboxaccount',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="User's email address from Dropbox", max_length=254),
        ),
    ]
